apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: devops
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
  type: ClusterIP
