apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: devops
data:
  config.hcl: |
    ui = true
    disable_mlock = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "file" {
      path = "/vault/data"
    }

    api_addr = "http://0.0.0.0:8200"

