apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: devops
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.16.3
          imagePullPolicy: IfNotPresent
          command:
            - "vault"
            - "server"
            - "-config=/vault/config/config.hcl"
          ports:
            - containerPort: 8200
              name: vault
          env:
            - name: VAULT_ADDR
              value: "http://127.0.0.1:8200"
          # Tambah privilege agar bisa IPC_LOCK tanpa error
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
            runAsUser: 100
            runAsGroup: 1000
            runAsNonRoot: true
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
              readOnly: true
            - name: vault-data
              mountPath: /vault/data
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
        - name: vault-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: devops
spec:
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  selector:
    app: vault

