apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-role
  namespace: devops
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-rolebinding
  namespace: devops
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: devops
roleRef:
  kind: Role
  name: vault-role
  apiGroup: rbac.authorization.k8s.io
