apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      securityContext:
        runAsNonRoot: true
        fsGroup: 1000
      containers:
        - name: vault
          image: hashicorp/vault:1.17.3
          imagePullPolicy: IfNotPresent
          args:
            - "server"
            - "-config=/vault/config/vault.hcl"
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_ADDR
              value: "http://0.0.0.0:8200"
            - name: VAULT_API_ADDR
              value: "http://vault.devops.svc.cluster.local:8200"
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: vault-data
              mountPath: /vault/file
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
            allowPrivilegeEscalation: false
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-pvc
