- name: Get current directory
  shell: pwd
  register: current_workdir
  connection: local

- name: Get bome directory
  shell: echo $HOME
  register: home_workdir
  connection: local

- name: Assign to variable
  set_fact:
    cwd: "{{ current_workdir.stdout }}"
  connection: local

- name: Assign to variable
  set_fact:
    homedir: "{{ home_workdir.stdout }}"
  connection: local
  
- name: include variable
  include_vars:
    file: "./vars/rundeck.yaml"
    name: rundeck
  connection: local

- name: Create ddb pipeline rundeck folder
  file:
    path: "$HOME/.ddb-pipeline-rundeck/"
    state: directory
    mode: 0777
  
- name: Create config folder
  file:
    path: "$HOME/.ddb-pipeline-rundeck/{{ rundeck.project_name }}-{{ envDeployment }}/{{ rundeck.project_name }}-{{ envDeployment }}/{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - config
  
- name: Temp config and secret location
  set_fact:
    tempLocation: "{{ homedir }}/.ddb-pipeline-rundeck/{{ rundeck.project_name }}-{{ envDeployment }}/{{ rundeck.project_name }}-{{ envDeployment }}/"
  

- name: Merge variable configFiles and secretFiles
  set_fact:
    configFiles: "{{ project.configFiles }}"
  connection: local
  
- name: Copy configuration files
  template: 
    src="{{ cwd }}/../{{ projectFolder }}/{{ item.src }}" 
    dest="$HOME/.ddb-pipeline-rundeck/{{ rundeck.project_name }}-{{ envDeployment }}/{{ rundeck.project_name }}-{{ envDeployment }}/{{ item.dest }}"  
  connection: local
  with_items:  "{{ project.configFiles }}"

- name: Create init.sh
  template: 
    src: "templates/init.sh"
    dest: "$HOME/.ddb-pipeline-rundeck/{{ rundeck.project_name }}-{{ envDeployment }}/{{ rundeck.project_name }}-{{ envDeployment }}/{{ item.name }}.sh"
  connection: local
  with_items: "{{ rundeck.jobs }}"
  








