apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: devops
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-nodes'
        static_configs:
          - targets: ['node-exporter.devops.svc.cluster.local:9100']

      - job_name: 'mysql-exporter'
        static_configs:
          - targets: ['mysql-exporter.devops.svc.cluster.local:9104']

      - job_name: 'goapi'
        static_configs:
          - targets: ['goapi-service.devops.svc.cluster.local:8080']

      - job_name: 'laravel'
        static_configs:
          - targets: ['laravel-service.devops.svc.cluster.local:8001']

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.devops.svc.cluster.local:8080']
