- hosts: 
  - k8s-production  
  vars:
    conection: local
    envDeployment: production
    projectFolder: ''
    project:
      rundeck:
        apiVersion: 35
        host: "{{ rundeck_host }}"
        #host: http://172.18.224.75:8080
        rundeck_token: "{{ rundeck_token }}"
        is_enabled: "{{ rundeck_is_enabled }}"
        is_scheduled: "{{ rundeck_is_scheduled }}"
      # slack:
      #   token: "{{ slack_token }}"
      #   channel: "#monitoring-general"
      main_container:
        image: "{{ image_name }}"
        tag: "{{ tag }}"
      configFiles: 
        - src: .env
          dest: .env
          mountPath: /go/src/goapp/.env
        
  roles:
    - {role: rundeck}
