apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapi
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      containers:
        - name: goapi
          image: sotar12/go:latest    # ganti dengan image kamu
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: goapi-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: goapi
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32156
