apiVersion: v1
kind: ServiceAccount
metadata:
  name: laravel
  namespace: devops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
      annotations:
        # === VAULT AGENT INJECTOR ===
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "laravel"
        vault.hashicorp.com/agent-inject-secret-env: "secret/laravel"
        vault.hashicorp.com/agent-inject-template-env: |
          {{- with secret "secret/laravel" -}}
          APP_NAME=Laravel
          APP_ENV=production
          APP_KEY={{ .Data.data.APP_KEY }}
          APP_DEBUG=false
          APP_URL=http://localhost
          DB_CONNECTION=mysql
          DB_HOST={{ .Data.data.DB_HOST }}
          DB_PORT=3306
          DB_DATABASE={{ .Data.data.DB_DATABASE }}
          DB_USERNAME={{ .Data.data.DB_USERNAME }}
          DB_PASSWORD={{ .Data.data.DB_PASSWORD }}
          {{- end }}
    spec:
      serviceAccountName: laravel
      containers:
        - name: laravel
          image: sotar12/laravel:latest
          ports:
            - containerPort: 8001
          command: ["sh", "-c"]
          args:
            - php artisan key:generate --force && php artisan serve --host=0.0.0.0 --port=8001
          volumeMounts:
            - name: storage
              mountPath: /var/www/html/storage
      volumes:
        - name: storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 31408
