apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: sotar123
  MYSQL_DATABASE: laravel
  MYSQL_USER: sotar 
  MYSQL_PASSWORD: sotar123
