project_name: "cicd-sch-deo"
jobs:
  - name: "cicd-sch-deo"
    volumes:
      - name: cicd-sch-deo
        mountPath: /go/src/goapp/log
    docker:
      extraArgs: []
        # - name: dns
        # value: "172.18.97.204"
    timeZone: Asia/Jakarta
    enabled: "{{ project.rundeck.is_enabled }}"
    schedule:
      enabled: "{{ project.rundeck.is_scheduled }}"
      cron:
        dayofmonth:
          day: '*'
        month: '*'
        time:
          hour: '1'
          minute: '0'
          seconds: '0'
        year: '*'
    sequence:
      keepgoing: false
      strategy: node-first
      commands:
        - script: |-
            bash -c "go run main.go --job=cicd-sch-deo"

