apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-template
  namespace: devops
data:
  mysql.ctmpl: |
    MYSQL_USER={{ with secret "secret/data/devops/mysql" }}{{ .Data.data.MYSQL_USER }}{{ end }}
    MYSQL_PASSWORD={{ with secret "secret/data/devops/mysql" }}{{ .Data.data.MYSQL_PASSWORD }}{{ end }}
    MYSQL_DATABASE={{ with secret "secret/data/devops/mysql" }}{{ .Data.data.MYSQL_DATABASE }}{{ end }}
    MYSQL_HOST={{ with secret "secret/data/devops/mysql" }}{{ .Data.data.MYSQL_HOST }}{{ end }}
    MYSQL_PORT={{ with secret "secret/data/devops/mysql" }}{{ .Data.data.MYSQL_PORT }}{{ end }}

